---
  - name: restart-logstash-indexer
    service: name=logstash-indexer state=restarted enabled=yes
  - name: restart-logstash-shipper
    service: name=logstash-shipper state=restarted enabled=yes
  - name: start-logstash-shipper
    service: name=logstash-shipper state=started enabled=yes
  - name: restart-logstash-web
    service: name=logstash-web state=restarted enabled=yes