---
 # - name: 'prepare server for MariaDB'
 #   copy: src=../files/MariaDB.repo dest=/etc/yum.repos.d/ mode=764 owner=root group=root
 #   when: "'{{ ansible_eth0.ipv4.address }}' in groups['all-mariadb']"
  - name: 'Install MySQL'
    yum: name={{ item }} state=present
    with_items:
    - MySQL-python
    - mysql
    - mysql-server
    notify:
     - restart-mysql
  - name: 'Start Mysql Service'
    action: service name=mysqld state=started enabled=yes
  - name: 'Update Mysql Root Password'
    mysql_user: name=root host=localhost password={{ mysql_root_password }} state=present
  - name: 'Copy Conf file with root password credentials'
    template: src=../templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=600
  - name: 'Copy Conf file to Admin home folder'
    template: src=../templates/my.cnf.j2 dest=/home/admin/.my.cnf owner=admin mode=600
  - name: 'Update Rest-Mysql Root Password'
    mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
    with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_eth0.ipv4.address }}"
    - 127.0.0.1
    - ::1
  - name: 'Delete anonymous MySQL server user from server'
    mysql_user: name="" host={{ ansible_hostname }} state="absent"
  - name: 'Delete anonymouse MySQL account for localhost'
    mysql_user: name="" state="absent"
