---
  - name: 'Check Mysql-Server Install Status'
    shell: "mysql -V | awk '{ print $5}' | awk -F, '{print $1}'"
    register: mysql_status
    ignore_errors: True
 #   failed_when: "'No' in mysql_status.stderr"
    changed_when: False
 # - debug: msg="{{ mysql_status }}"
  - name: 'Checking once again on Mysql Installation'
    shell: ls /etc/init.d/mysql*
    register: mysql_init
    when: mysql_status.stdout != '10.0.3-MariaDB'
    ignore_errors: True
 #   failed_when: "'No' in mysql_init.stderr"
    changed_when: False
 # - debug: msg="{{ mysql_init }}"
  - name: 'Prepare server for MariaDB(Repo-Setup)'
    copy: src=../files/MariaDB.repo dest=/etc/yum.repos.d/ mode=644 owner=root group=root
    when: "'{{ ansible_eth0.ipv4.address }}' in groups['all-mariadb']"
  - name: 'Installing MariaDB-Mysql-Server' 
    yum: name={{ item }} state=installed
    with_items:
    - MySQL-python
    - MariaDB-client
    - MariaDB-server
    - php-mysql
    when: mysql_status.stdout != "10.0.3-MariaDB" and mysql_init.rc != "0"
  - name: Create Data Directory 
    file: path={{ datadir }} owner=mysql group=company mode=766 state=directory recurse=yes
  - name: 'Copy Conf file with root password credentials'
    template: src=../templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=600
  - name: 'Copy Conf file to Admin home folder'
    template: src=../templates/my.cnf.j2 dest=/home/admin/.my.cnf owner=admin mode=600
  - name: 'Server CNF rollout'
    template: src=../templates/server.cnf.j2 dest=/etc/my.cnf.d/server.cnf mode=644 owner=root group=root
    notify:
    - restart-mysql
  - name: 'Initiate DB for new install'
    shell: mysql_install_db --user=mysql --ldata={{ datadir }}
    when: mysql_status.stdout != "10.0.3-MariaDB" and mysql_init.rc != "0"
  - name: 'Update Rest-Mysql Root Password'
    mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present
    with_items:
    - "{{ ansible_hostname }}"
    - "{{ ansible_eth0.ipv4.address }}"
    - 127.0.0.1
    - localhost
    - ::1
  - name: 'Delete anonymous MySQL server user from server'
    mysql_user: name="" host={{ ansible_hostname }} state="absent"
  - name: 'Delete anonymouse MySQL account for localhost'
    mysql_user: name="" state="absent"

# The following Grants to be added - 
# GRANT ALL PRIVILEGES ON data_analytics.* To 'analytics'@'%' IDENTIFIED BY '!a#cy2';
# GRANT ALL PRIVILEGES ON PAYMENTS.* To 'pos'@'%' IDENTIFIED BY 'vitnav';
# GRANT ALL PRIVILEGES ON data_email.* To 'email_user'@'%' IDENTIFIED BY 'e789m#@';
#  - name: 'Fresh Schema Rollout'
#    copy: src=../files/{{ CASS_SCHEMA }} dest={{ install_dir }}/{{ CASS_SCHEMA }} force=no owner=test_user group=company mode=0766
# PAYMENT, BI and OPENFIRE 
#    when: mysql_status.stdout != "10.0.3-MariaDB" and mysql_init.rc != "0" 
#  - name: 'Schema Update'
#    shell: echo "HEllo {{ schema_update.changed }}"
